//! Connection test between two connected devices (D48).
//!
//! Each direction rides its own bidirectional stream, like an object. The
//! requester sends an `ObjectRequest` with `speed_test` set; the answering
//! device accepts with an `ObjectHeader`. For a download it then writes
//! generated bytes until the duration is up; for an upload the requester
//! does, and the answering device replies with a `SpeedTestDone` saying
//! what arrived. QUIC encrypts every byte and nothing compresses, so zeros
//! measure the same as random data. No disk is involved on either side.

use std::sync::Arc;
use std::time::{Duration, Instant};

use quinn::{Connection, RecvStream, SendStream};
use relay_core::DeviceId;
use relay_core::format_socket_addr;
use relay_core::remote::{RemoteError, RemoteErrorCode};
use relay_core::speed::{
    PathKind, SPEED_SAMPLE_MS, SPEED_TEST_MAX_MS, SpeedLeg, SpeedReport, add_sample,
};
use relay_proto::{
    FEATURE_SPEED_TEST, ObjectHeader, ObjectRequest, SpeedTestDone, SpeedTestRequest, encode_frame,
    error_to_wire,
};

use crate::io::read_message_max;
use crate::relay::virtual_peer_addr;
use crate::session::{Inner, OBJECT_HEADER_MAX};

const CHUNK: usize = 64 * 1024;
/// How long the requester waits for the answering device to accept.
const ACCEPT_TIMEOUT: Duration = Duration::from_secs(10);
/// A test stream that goes quiet for this long has failed.
const IDLE_TIMEOUT: Duration = Duration::from_secs(10);
/// What an upload's receiver allows past the duration before it stops
/// counting: queued bytes still drain after the sender's clock runs out.
const DRAIN_GRACE: Duration = Duration::from_secs(15);
static ZEROS: [u8; CHUNK] = [0; CHUNK];

/// Run a download then an upload against `peer`, each for `duration_ms`.
pub(crate) async fn run(
    inner: Arc<Inner>,
    peer: DeviceId,
    duration_ms: u32,
) -> Result<SpeedReport, RemoteError> {
    let Some(conn) = inner.control_connection(peer) else {
        return Err(RemoteError::new(
            RemoteErrorCode::Offline,
            "that device is not connected",
        ));
    };
    if !inner.peer_has_feature(peer, FEATURE_SPEED_TEST) {
        return Err(RemoteError::new(
            RemoteErrorCode::Unsupported,
            "that device runs a Relay without connection tests; update it",
        ));
    }
    let _running = inner
        .speed_tests_out
        .clone()
        .try_acquire_owned()
        .map_err(|_| {
            RemoteError::new(
                RemoteErrorCode::Busy,
                "a connection test is already running",
            )
        })?;
    let duration_ms = duration_ms.clamp(1, SPEED_TEST_MAX_MS);
    let limit =
        Duration::from_millis(u64::from(duration_ms)) * 2 + 2 * ACCEPT_TIMEOUT + DRAIN_GRACE;

    let before = conn.stats().path;
    let legs = async {
        let download = download(&conn, duration_ms).await?;
        let upload = upload(&conn, duration_ms).await?;
        Ok::<_, RemoteError>((download, upload))
    };
    let (download, upload) = tokio::time::timeout(limit, legs)
        .await
        .map_err(|_| RemoteError::new(RemoteErrorCode::Timeout, "the connection test stalled"))??;
    let after = conn.stats().path;

    let remote = conn.remote_address();
    let path = if remote == virtual_peer_addr(peer) {
        PathKind::Relayed
    } else {
        PathKind::of_direct(remote.ip())
    };
    Ok(SpeedReport {
        path,
        address: format_socket_addr(remote),
        rtt_us: u64::try_from(conn.rtt().as_micros()).unwrap_or(u64::MAX),
        mtu: after.current_mtu,
        sent_packets: after.sent_packets.saturating_sub(before.sent_packets),
        lost_packets: after.lost_packets.saturating_sub(before.lost_packets),
        sample_ms: SPEED_SAMPLE_MS,
        download,
        upload,
    })
}

/// Open a test stream and wait for the answering device to accept it.
async fn open(
    conn: &Connection,
    request: SpeedTestRequest,
) -> Result<(SendStream, RecvStream), RemoteError> {
    let (mut send, mut recv) = conn.open_bi().await.map_err(failed)?;
    let frame = encode_frame(&ObjectRequest {
        speed_test: Some(request),
        ..Default::default()
    })
    .map_err(failed)?;
    send.write_all(&frame).await.map_err(failed)?;
    let header: ObjectHeader = tokio::time::timeout(
        ACCEPT_TIMEOUT,
        read_message_max(&mut recv, OBJECT_HEADER_MAX),
    )
    .await
    .map_err(|_| {
        RemoteError::new(
            RemoteErrorCode::Timeout,
            "that device did not answer in time",
        )
    })?
    .map_err(failed)?;
    if let Some(err) = header.error {
        return Err(relay_proto::error_from_wire(err));
    }
    if !header.found {
        return Err(RemoteError::new(
            RemoteErrorCode::Unsupported,
            "that device refused the connection test",
        ));
    }
    Ok((send, recv))
}

async fn download(conn: &Connection, duration_ms: u32) -> Result<SpeedLeg, RemoteError> {
    let request = SpeedTestRequest {
        upload: false,
        duration_ms,
    };
    let (mut send, mut recv) = open(conn, request).await?;
    send.finish().map_err(failed)?;
    let (bytes, elapsed_us, samples) = count(&mut recv, None).await?;
    Ok(SpeedLeg::new(bytes, elapsed_us, samples))
}

async fn upload(conn: &Connection, duration_ms: u32) -> Result<SpeedLeg, RemoteError> {
    let request = SpeedTestRequest {
        upload: true,
        duration_ms,
    };
    let (mut send, mut recv) = open(conn, request).await?;
    let samples = blast(&mut send, Duration::from_millis(u64::from(duration_ms))).await?;
    send.finish().map_err(failed)?;
    let done: SpeedTestDone =
        tokio::time::timeout(DRAIN_GRACE, read_message_max(&mut recv, OBJECT_HEADER_MAX))
            .await
            .map_err(|_| {
                RemoteError::new(
                    RemoteErrorCode::Timeout,
                    "that device did not report the upload",
                )
            })?
            .map_err(failed)?;
    Ok(SpeedLeg::new(done.bytes, done.elapsed_us, samples))
}

/// Write zeros for `duration`. Returns bytes written per sample window.
async fn blast(send: &mut SendStream, duration: Duration) -> Result<Vec<u64>, RemoteError> {
    let start = Instant::now();
    let mut samples = Vec::new();
    loop {
        let elapsed = start.elapsed();
        if elapsed >= duration {
            return Ok(samples);
        }
        let n = tokio::time::timeout(IDLE_TIMEOUT, send.write(&ZEROS))
            .await
            .map_err(|_| RemoteError::new(RemoteErrorCode::Timeout, "the connection stalled"))?
            .map_err(failed)?;
        let at = u64::try_from(start.elapsed().as_micros()).unwrap_or(u64::MAX);
        add_sample(&mut samples, at, SPEED_SAMPLE_MS, n as u64);
    }
}

/// Read to the end of the stream, or until `deadline`. Returns bytes, the
/// time from the first byte to the last, and bytes per sample window.
async fn count(
    recv: &mut RecvStream,
    deadline: Option<Instant>,
) -> Result<(u64, u64, Vec<u64>), RemoteError> {
    let mut buf = vec![0u8; CHUNK];
    let mut bytes = 0u64;
    let mut first: Option<Instant> = None;
    let mut last = Instant::now();
    let mut samples = Vec::new();
    loop {
        if deadline.is_some_and(|d| Instant::now() >= d) {
            break;
        }
        let read = tokio::time::timeout(IDLE_TIMEOUT, recv.read(&mut buf))
            .await
            .map_err(|_| RemoteError::new(RemoteErrorCode::Timeout, "the connection stalled"))?
            .map_err(failed)?;
        let Some(n) = read else {
            break;
        };
        last = Instant::now();
        let start = *first.get_or_insert(last);
        let at = u64::try_from(last.duration_since(start).as_micros()).unwrap_or(u64::MAX);
        add_sample(&mut samples, at, SPEED_SAMPLE_MS, n as u64);
        bytes += n as u64;
    }
    let elapsed_us = first.map_or(0, |start| {
        u64::try_from(last.duration_since(start).as_micros()).unwrap_or(u64::MAX)
    });
    Ok((bytes, elapsed_us, samples))
}

/// Answer one test stream from a trusted peer.
pub(crate) async fn serve(
    inner: &Inner,
    peer: DeviceId,
    mut send: SendStream,
    mut recv: RecvStream,
    request: SpeedTestRequest,
) -> Result<(), String> {
    // One test at a time on this device, whoever asks: two would each
    // measure half the link.
    let Ok(_permit) = inner.speed_tests_in.clone().try_acquire_owned() else {
        let err = RemoteError::new(
            RemoteErrorCode::Busy,
            "a connection test is already running",
        );
        let header = ObjectHeader {
            error: Some(error_to_wire(&err)),
            ..Default::default()
        };
        let bytes = encode_frame(&header).map_err(|e| e.to_string())?;
        send.write_all(&bytes).await.map_err(|e| e.to_string())?;
        let _ = send.finish();
        return Ok(());
    };
    tracing::debug!(peer = %peer, upload = request.upload, "connection test");
    let accept = encode_frame(&ObjectHeader {
        found: true,
        ..Default::default()
    })
    .map_err(|e| e.to_string())?;
    send.write_all(&accept).await.map_err(|e| e.to_string())?;
    let duration =
        Duration::from_millis(u64::from(request.duration_ms.clamp(1, SPEED_TEST_MAX_MS)));
    if request.upload {
        let deadline = Instant::now() + duration + DRAIN_GRACE;
        let (bytes, elapsed_us, _) = count(&mut recv, Some(deadline))
            .await
            .map_err(|e| e.to_string())?;
        let _ = recv.stop(0u32.into());
        let done = encode_frame(&SpeedTestDone { bytes, elapsed_us }).map_err(|e| e.to_string())?;
        send.write_all(&done).await.map_err(|e| e.to_string())?;
    } else {
        blast(&mut send, duration)
            .await
            .map_err(|e| e.to_string())?;
    }
    let _ = send.finish();
    Ok(())
}

fn failed(err: impl ToString) -> RemoteError {
    RemoteError::new(RemoteErrorCode::Failed, err.to_string())
}
