//! Connection test between two connected devices (D48).
//!
//! The answering device streams generated bytes for a while, then the
//! caller does the same the other way. Nothing touches a disk, so the
//! numbers are the link's, not the store's.

use std::net::IpAddr;

use serde::{Deserialize, Serialize};

use crate::addr::{is_tailscale_v4, is_tailscale_v6};

/// Each direction runs this long unless the caller asks otherwise.
pub const SPEED_TEST_DEFAULT_MS: u32 = 5_000;
/// Longest one direction may run. The answering device clamps to it too.
pub const SPEED_TEST_MAX_MS: u32 = 10_000;
/// Width of one throughput sample.
pub const SPEED_SAMPLE_MS: u32 = 250;

/// How the connection reaches the other device.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PathKind {
    /// Same machine.
    Loopback,
    /// A private or link-local address: the same network.
    Lan,
    Tailscale,
    /// A public address: a hole-punched or forwarded direct path.
    Internet,
    /// Through the UDP forwarder (D34).
    Relayed,
}

impl PathKind {
    /// Classify a direct (not relayed) remote address.
    pub fn of_direct(ip: IpAddr) -> Self {
        let ip = match ip {
            IpAddr::V6(v6) => v6.to_ipv4_mapped().map_or(ip, IpAddr::V4),
            v4 => v4,
        };
        match ip {
            IpAddr::V4(v) if v.is_loopback() => Self::Loopback,
            IpAddr::V4(v) if is_tailscale_v4(v) => Self::Tailscale,
            IpAddr::V4(v) if v.is_private() || v.is_link_local() => Self::Lan,
            IpAddr::V6(v) if v.is_loopback() => Self::Loopback,
            IpAddr::V6(v) if is_tailscale_v6(v) => Self::Tailscale,
            // fe80::/10 link-local, fc00::/7 unique local.
            IpAddr::V6(v)
                if (v.segments()[0] & 0xffc0) == 0xfe80 || (v.segments()[0] & 0xfe00) == 0xfc00 =>
            {
                Self::Lan
            }
            _ => Self::Internet,
        }
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Loopback => "loopback",
            Self::Lan => "LAN",
            Self::Tailscale => "Tailscale",
            Self::Internet => "internet",
            Self::Relayed => "relayed",
        }
    }
}

/// One direction of a test.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct SpeedLeg {
    /// Bytes the receiving side counted.
    pub bytes: u64,
    /// From the first byte to the last, on the receiving side.
    pub elapsed_ms: u64,
    pub bits_per_sec: u64,
    /// Bytes per [`SpeedReport::sample_ms`] window, in order. For an upload
    /// these are what this side handed to QUIC, which runs ahead of the
    /// receiver by at most the flow-control window.
    pub samples: Vec<u64>,
}

impl SpeedLeg {
    pub fn new(bytes: u64, elapsed_us: u64, samples: Vec<u64>) -> Self {
        let bits_per_sec = if elapsed_us == 0 {
            0
        } else {
            u64::try_from(u128::from(bytes) * 8 * 1_000_000 / u128::from(elapsed_us))
                .unwrap_or(u64::MAX)
        };
        Self {
            bytes,
            elapsed_ms: elapsed_us / 1_000,
            bits_per_sec,
            samples,
        }
    }
}

/// The result of one connection test.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SpeedReport {
    pub path: PathKind,
    /// The other device's address as this connection sees it.
    pub address: String,
    /// QUIC's smoothed round trip at the end of the test.
    pub rtt_us: u64,
    /// UDP payload size the connection settled on.
    pub mtu: u16,
    /// Packets this side sent and declared lost during the test.
    pub sent_packets: u64,
    pub lost_packets: u64,
    pub sample_ms: u32,
    /// The other device sending to this one.
    pub download: SpeedLeg,
    /// This device sending to the other.
    pub upload: SpeedLeg,
}

/// Index of the [`SPEED_SAMPLE_MS`] window `elapsed_us` falls in.
pub fn sample_index(elapsed_us: u64, sample_ms: u32) -> usize {
    usize::try_from(elapsed_us / (u64::from(sample_ms.max(1)) * 1_000)).unwrap_or(usize::MAX)
}

/// Add `bytes` to the window `elapsed_us` falls in, growing `samples`.
pub fn add_sample(samples: &mut Vec<u64>, elapsed_us: u64, sample_ms: u32, bytes: u64) {
    // A window past the test's end (a late tail) folds into the last one
    // the test can have, so a stalled read cannot grow the vector.
    let cap = (SPEED_TEST_MAX_MS / sample_ms.max(1)) as usize + 1;
    let at = sample_index(elapsed_us, sample_ms).min(cap - 1);
    if samples.len() <= at {
        samples.resize(at + 1, 0);
    }
    samples[at] += bytes;
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::net::{Ipv4Addr, Ipv6Addr};

    #[test]
    fn paths_classify() {
        let v4 = |a, b, c, d| IpAddr::V4(Ipv4Addr::new(a, b, c, d));
        assert_eq!(PathKind::of_direct(v4(127, 0, 0, 1)), PathKind::Loopback);
        assert_eq!(PathKind::of_direct(v4(192, 168, 1, 4)), PathKind::Lan);
        assert_eq!(PathKind::of_direct(v4(10, 0, 0, 4)), PathKind::Lan);
        assert_eq!(PathKind::of_direct(v4(100, 101, 2, 3)), PathKind::Tailscale);
        assert_eq!(PathKind::of_direct(v4(81, 2, 3, 4)), PathKind::Internet);
        let mapped = IpAddr::V6(Ipv4Addr::new(192, 168, 1, 4).to_ipv6_mapped());
        assert_eq!(PathKind::of_direct(mapped), PathKind::Lan);
        let ula: Ipv6Addr = "fd12::1".parse().unwrap();
        assert_eq!(PathKind::of_direct(IpAddr::V6(ula)), PathKind::Lan);
        let ts: Ipv6Addr = "fd7a:115c:a1e0::1".parse().unwrap();
        assert_eq!(PathKind::of_direct(IpAddr::V6(ts)), PathKind::Tailscale);
        let global: Ipv6Addr = "2001:db8::1".parse().unwrap();
        assert_eq!(PathKind::of_direct(IpAddr::V6(global)), PathKind::Internet);
    }

    #[test]
    fn rate_and_samples() {
        let leg = SpeedLeg::new(125_000_000, 1_000_000, vec![]);
        assert_eq!(leg.bits_per_sec, 1_000_000_000);
        assert_eq!(leg.elapsed_ms, 1_000);
        assert_eq!(SpeedLeg::new(10, 0, vec![]).bits_per_sec, 0);

        let mut samples = Vec::new();
        add_sample(&mut samples, 0, 250, 5);
        add_sample(&mut samples, 260_000, 250, 7);
        add_sample(&mut samples, 3_600_000_000, 250, 1);
        assert_eq!(samples[0], 5);
        assert_eq!(samples[1], 7);
        assert_eq!(samples.len(), 41, "a late tail folds into the last window");
        assert_eq!(samples[40], 1);
    }
}
