[package]
name = "relay-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
directories.workspace = true
dunce = "1"
hex.workspace = true
relay-core.workspace = true
relay-crypto.workspace = true
relay-db.workspace = true
relay-fs.workspace = true
relay-policy.workspace = true
relay-proto.workspace = true
relay-replica.workspace = true
relay-store.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
proptest.workspace = true
relay-core.workspace = true
relay-fs.workspace = true
relay-proto.workspace = true
relay-replica.workspace = true
rusqlite.workspace = true
tempfile.workspace = true

[lints]
workspace = true
